/** C（libcurl / libwebsockets / libuv-ws / wslay）代码生成 */

import { esc, parseWsUrl, Req, WsReq } from "./shared";
export function genC(r: Req): string {
  const out: string[] = [];
  if (r.files.length) {
    out.push("// 该表单包含文件上传（multipart/form-data），请使用 curl_formadd() 构造 multipart 请求");
  }
  out.push("#include <stdio.h>");
  out.push("#include <string.h>");
  out.push("#include <curl/curl.h>");
  out.push("");
  out.push("static size_t write_cb(void *ptr, size_t size, size_t nmemb, void *userdata) {");
  out.push("    (void)userdata;");
  out.push("    return fwrite(ptr, size, nmemb, stdout);");
  out.push("}");
  out.push("");
  out.push("int main(void) {");
  out.push("    CURL *curl = curl_easy_init();");
  out.push("    if (!curl) return 1;");
  out.push("    struct curl_slist *headers = NULL;");
  for (const h of r.headers) {
    out.push(`    headers = curl_slist_append(headers, "${esc(`${h.key}: ${h.value}`, '"')}");`);
  }
  out.push(`    curl_easy_setopt(curl, CURLOPT_URL, "${esc(r.url, '"')}");`);
  out.push(`    curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "${r.method}");`);
  if (r.headers.length) out.push("    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);");
  if (r.body) {
    out.push(`    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "${esc(r.body, '"')}");`);
    out.push(`    curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, (long)strlen("${esc(r.body, '"')}"));`);
  }
  out.push("    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_cb);");
  out.push("    CURLcode res = curl_easy_perform(curl);");
  out.push("    curl_slist_free_all(headers);");
  out.push("    curl_easy_cleanup(curl);");
  out.push("    return res != CURLE_OK;");
  out.push("}");
  return out.join("\n");
}

export function genWsC(r: WsReq, lib?: string): string {
  switch (lib) {
    case "libuvws":
      return genWsCLibuvws(r);
    case "wslay":
      return genWsCWslay(r);
    default:
      return genWsCLibwebsockets(r);
  }
}

export function genWsCLibwebsockets(r: WsReq): string {
  const u = parseWsUrl(r.url);
  const out: string[] = [];
  out.push("/*");
  out.push(" * WebSocket 客户端示例（libwebsockets）");
  out.push(" * 官网: https://libwebsockets.org");
  out.push(" * GitHub: https://github.com/warmcat/libwebsockets");
  out.push(" * 安装: sudo apt install libwebsockets-dev    (Ubuntu/Debian)");
  out.push(" *       brew install libwebsockets             (macOS)");
  out.push(" * 编译: gcc -o ws_client ws_client.c -lwebsockets");
  out.push(" *       （连接 wss:// 时需另链接 OpenSSL: -lssl -lcrypto，并启用下方 wss 两行）");
  out.push(" *");
  for (const h of r.headers) out.push(` * 请求头: ${h.key}: ${h.value}（通过 LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER 回调追加）`);
  out.push(" */");
  out.push("#include <stdio.h>");
  out.push("#include <string.h>");
  out.push("#include <libwebsockets.h>");
  out.push("");
  out.push(`#define MSG ${JSON.stringify(r.message || "hello, this is a websocket echo message")}`);
  out.push("");
  out.push("static int g_done = 0;");
  out.push("");
  out.push("static int ws_callback(struct lws *wsi, enum lws_callback_reasons reason,");
  out.push("                       void *user, void *in, size_t len) {");
  out.push("    (void)user;");
  out.push("    switch (reason) {");
  out.push("    case LWS_CALLBACK_CLIENT_ESTABLISHED: {");
  out.push("        unsigned char buf[LWS_PRE + 512];");
  out.push("        size_t n = strlen(MSG);");
  out.push("        if (n > sizeof(buf) - LWS_PRE - 1) n = sizeof(buf) - LWS_PRE - 1;");
  out.push("        memcpy(buf + LWS_PRE, MSG, n);");
  out.push("        printf(\">>> 发送: %s\\n\", MSG);");
  out.push("        lws_write(wsi, buf + LWS_PRE, n, LWS_WRITE_TEXT);");
  out.push("        break;");
  out.push("    }");
  out.push("    case LWS_CALLBACK_CLIENT_RECEIVE:");
  out.push("        printf(\"<<< 接收: %.*s\\n\", (int)len, (const char *)in);");
  out.push("        g_done = 1;");
  out.push("        break;");
  out.push("    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:");
  out.push("        fprintf(stderr, \"连接失败\\n\");");
  out.push("        g_done = 1;");
  out.push("        break;");
  out.push("    case LWS_CALLBACK_CLIENT_CLOSED:");
  out.push("        g_done = 1;");
  out.push("        break;");
  out.push("    default:");
  out.push("        break;");
  out.push("    }");
  out.push("    return 0;");
  out.push("}");
  out.push("");
  out.push("static const struct lws_protocols protocols[] = {");
  out.push("    { \"api-manager\", ws_callback, 0, 4096, 0, NULL, 0 },");
  out.push("    LWS_PROTOCOL_LIST_TERM");
  out.push("};");
  out.push("");
  out.push("int main(void) {");
  out.push("    struct lws_context_creation_info info;");
  out.push("    memset(&info, 0, sizeof(info));");
  out.push("    info.port = CONTEXT_PORT_NO_LISTEN;");
  out.push("    info.protocols = protocols;");
  out.push("    struct lws_context *ctx = lws_create_context(&info);");
  out.push("    if (!ctx) {");
  out.push("        fprintf(stderr, \"创建上下文失败\\n\");");
  out.push("        return 1;");
  out.push("    }");
  out.push("");
  out.push("    struct lws_client_connect_info cci;");
  out.push("    memset(&cci, 0, sizeof(cci));");
  out.push("    cci.context = ctx;");
  out.push(`    cci.address = ${JSON.stringify(u.host)};`);
  out.push(`    cci.port = ${u.port};`);
  out.push(`    cci.path = ${JSON.stringify(u.path)};`);
  out.push("    cci.host = cci.address;   /* Host 请求头 */");
  out.push("    cci.origin = \"api-manager\";");
  out.push("    cci.protocol = protocols[0].name;");
  if (u.scheme === "wss") {
    out.push("    cci.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED; /* wss */");
  } else {
    out.push("    /* wss: cci.ssl_connection = LCCSCF_USE_SSL | LCCSCF_ALLOW_SELFSIGNED; */");
  }
  out.push("    if (!lws_client_connect_via_info(&cci)) {");
  out.push("        fprintf(stderr, \"发起连接失败\\n\");");
  out.push("        lws_context_destroy(ctx);");
  out.push("        return 1;");
  out.push("    }");
  out.push("    while (!g_done) {");
  out.push("        lws_service(ctx, 50);");
  out.push("    }");
  out.push("    lws_context_destroy(ctx);");
  out.push("    return 0;");
  out.push("}");
  return out.join("\n");
}

export function genWsCLibuvws(r: WsReq): string {
  const out: string[] = [];
  out.push("/*");
  out.push(" * WebSocket 客户端示例（libuv-ws：基于 libuv 的轻量 WebSocket 库）");
  out.push(" * GitHub/官网: https://github.com/meojson/libuv-ws");
  out.push(" * 依赖:");
  out.push(" *   1. libuv:    sudo apt install libuv1-dev   (Ubuntu/Debian)");
  out.push(" *   2. libuv-ws: git clone https://github.com/meojson/libuv-ws");
  out.push(" * 编译: gcc -o ws_client ws_client.c uv_ws.c -I<libuv-ws目录> -luv -lpthread");
  out.push(" *       （将本文件与 libuv-ws 仓库根目录的 uv_ws.c 一起编译）");
  out.push(" *");
  for (const h of r.headers) out.push(` * 请求头: ${h.key}: ${h.value}（libuv-ws 不支持自定义请求头，请改用 query 参数/Cookie）`);
  out.push(" */");
  out.push("#include <stdio.h>");
  out.push("#include <string.h>");
  out.push("#include \"uv_ws.h\"");
  out.push("");
  out.push("static void on_open(uv_ws_client_t *client) {");
  out.push(`    const char *msg = ${JSON.stringify(r.message || "hello, this is a websocket echo message")};`);
  out.push("    printf(\">>> 发送: %s\\n\", msg);");
  out.push("    uv_ws_send(client, msg, strlen(msg));");
  out.push("}");
  out.push("");
  out.push("static void on_message(uv_ws_client_t *client, ssize_t size, uv_buf_t *buf) {");
  out.push("    printf(\"<<< 接收: %.*s\\n\", (int)size, buf->base);");
  out.push("    uv_ws_close(client); /* 收到回显后断开 */");
  out.push("}");
  out.push("");
  out.push("static void on_error(uv_ws_client_t *client) {");
  out.push("    fprintf(stderr, \"连接失败\\n\");");
  out.push("    uv_ws_close(client);");
  out.push("}");
  out.push("");
  out.push("static void on_close(uv_ws_client_t *client) {");
  out.push("    printf(\"连接已关闭\\n\");");
  out.push("}");
  out.push("");
  out.push("int main(void) {");
  out.push("    uv_loop_t *loop = uv_default_loop();");
  out.push("    uv_ws_client_t client;");
  out.push(`    uv_ws_init(loop, &client, ${JSON.stringify(r.url)});`);
  out.push("    client.on_open = on_open;");
  out.push("    client.on_message = on_message;");
  out.push("    client.on_error = on_error;");
  out.push("    client.on_close = on_close;");
  out.push("    uv_ws_connect(&client);");
  out.push("    return uv_run(loop, UV_RUN_DEFAULT);");
  out.push("}");
  return out.join("\n");
}

export function genWsCWslay(r: WsReq): string {
  const u = parseWsUrl(r.url);
  const out: string[] = [];
  out.push("/*");
  out.push(" * WebSocket 客户端示例（wslay：只做帧编解码，TCP 连接与 HTTP Upgrade 握手自行实现）");
  out.push(" * 官网/GitHub: https://github.com/tatsuhiro-t/wslay");
  out.push(" * 安装: sudo apt install libwslay-dev   (Ubuntu/Debian)");
  out.push(" * 编译: gcc -o ws_client ws_client.c -lwslay");
  out.push(" *");
  for (const h of r.headers) out.push(` * 请求头: ${h.key}: ${h.value}（已加入下方握手请求）`);
  out.push(" */");
  out.push("#include <stdio.h>");
  out.push("#include <stdint.h>");
  out.push("#include <stdlib.h>");
  out.push("#include <string.h>");
  out.push("#include <time.h>");
  out.push("#include <unistd.h>");
  out.push("#include <arpa/inet.h>");
  out.push("#include <sys/select.h>");
  out.push("#include <sys/socket.h>");
  out.push("#include <wslay/wslay.h>");
  out.push("");
  out.push("static int g_done = 0;");
  out.push("");
  out.push("/* 简易 base64 编码：用于生成握手所需的 Sec-WebSocket-Key */");
  out.push("static void base64_encode(const unsigned char *in, size_t len, char *out) {");
  out.push("    static const char tbl[] = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\";");
  out.push("    size_t i = 0, o = 0;");
  out.push("    while (i + 2 < len) {");
  out.push("        unsigned v = (in[i] << 16) | (in[i + 1] << 8) | in[i + 2];");
  out.push("        out[o++] = tbl[(v >> 18) & 63];");
  out.push("        out[o++] = tbl[(v >> 12) & 63];");
  out.push("        out[o++] = tbl[(v >> 6) & 63];");
  out.push("        out[o++] = tbl[v & 63];");
  out.push("        i += 3;");
  out.push("    }");
  out.push("    if (i < len) {");
  out.push("        unsigned v = (unsigned)in[i] << 16;");
  out.push("        if (i + 1 < len) v |= (unsigned)in[i + 1] << 8;");
  out.push("        out[o++] = tbl[(v >> 18) & 63];");
  out.push("        out[o++] = tbl[(v >> 12) & 63];");
  out.push("        out[o++] = (i + 1 < len) ? tbl[(v >> 6) & 63] : '=';");
  out.push("        out[o++] = '=';");
  out.push("    }");
  out.push("    out[o] = '\\0';");
  out.push("}");
  out.push("");
  out.push("/* wslay 回调：底层 socket 收发 + 收到消息时回调 */");
  out.push("static int send_cb(wslay_event_context_ptr ctx, const uint8_t *data, size_t len,");
  out.push("                    int flags, void *user_data) {");
  out.push("    (void)ctx; (void)flags;");
  out.push("    int fd = *(int *)user_data;");
  out.push("    return write(fd, data, len) == (ssize_t)len ? 0 : WSLAY_ERR_CALLBACK_FAILURE;");
  out.push("}");
  out.push("");
  out.push("static int recv_cb(wslay_event_context_ptr ctx, uint8_t *data, size_t len,");
  out.push("                    int flags, void *user_data) {");
  out.push("    (void)ctx; (void)flags;");
  out.push("    int fd = *(int *)user_data;");
  out.push("    ssize_t n = read(fd, data, len);");
  out.push("    return n < 0 ? WSLAY_ERR_CALLBACK_FAILURE : (int)n;");
  out.push("}");
  out.push("");
  out.push("static void msg_recv_cb(wslay_event_context_ptr ctx,");
  out.push("                        const struct wslay_event_on_msg_recv_arg *arg,");
  out.push("                        void *user_data) {");
  out.push("    (void)ctx; (void)user_data;");
  out.push("    if (arg->opcode == WSLAY_TEXT_FRAME || arg->opcode == WSLAY_BINARY_FRAME) {");
  out.push("        printf(\"<<< 接收: %.*s\\n\", (int)arg->msg_length, (const char *)arg->msg);");
  out.push("        g_done = 1;");
  out.push("    }");
  out.push("}");
  out.push("");
  out.push("static int genmask_cb(wslay_event_context_ptr ctx, uint8_t *buf, size_t len,");
  out.push("                      void *user_data) {");
  out.push("    (void)ctx; (void)user_data;");
  out.push("    size_t i;");
  out.push("    for (i = 0; i < len; ++i) buf[i] = (uint8_t)(rand() & 0xff);");
  out.push("    return 0;");
  out.push("}");
  out.push("");
  out.push("int main(void) {");
  out.push(`    const char *host = ${JSON.stringify(u.host)};`);
  out.push(`    int port = ${u.port};`);
  out.push(`    const char *path = ${JSON.stringify(u.path)};`);
  out.push("");
  out.push("    /* 1. 建立 TCP 连接 */");
  out.push("    int fd = socket(AF_INET, SOCK_STREAM, 0);");
  out.push("    if (fd < 0) { perror(\"socket\"); return 1; }");
  out.push("    struct sockaddr_in addr;");
  out.push("    memset(&addr, 0, sizeof(addr));");
  out.push("    addr.sin_family = AF_INET;");
  out.push("    addr.sin_port = htons((uint16_t)port);");
  out.push("    if (inet_pton(AF_INET, host, &addr.sin_addr) != 1) { perror(\"inet_pton\"); return 1; }");
  out.push("    if (connect(fd, (struct sockaddr *)&addr, sizeof(addr)) != 0) { perror(\"connect\"); return 1; }");
  out.push("");
  out.push("    /* 2. HTTP Upgrade 握手（Sec-WebSocket-Key 为 16 字节随机数的 base64；");
  out.push("         如需校验服务端 Sec-WebSocket-Accept，可另实现 SHA1 + base64） */");
  out.push("    char key_buf[24], req[1024];");
  out.push("    unsigned char raw[16];");
  out.push("    int i;");
  out.push("    srand((unsigned)time(NULL));");
  out.push("    for (i = 0; i < 16; ++i) raw[i] = (unsigned char)(rand() & 0xff);");
  out.push("    base64_encode(raw, sizeof(raw), key_buf);");
  out.push("    snprintf(req, sizeof(req),");
  out.push("             \"GET %s HTTP/1.1\\r\\n\"");
  out.push("             \"Host: %s:%d\\r\\n\"");
  out.push("             \"Upgrade: websocket\\r\\n\"");
  out.push("             \"Connection: Upgrade\\r\\n\"");
  for (const h of r.headers) {
    out.push(`             ${JSON.stringify(`${h.key}: ${h.value}\r\n`)}`);
  }
  out.push("             \"Sec-WebSocket-Key: %s\\r\\n\"");
  out.push("             \"Sec-WebSocket-Version: 13\\r\\n\\r\\n\",");
  out.push("             path, host, port, key_buf);");
  out.push("    if (write(fd, req, strlen(req)) != (ssize_t)strlen(req)) { perror(\"write\"); return 1; }");
  out.push("    char resp[1024];");
  out.push("    ssize_t n = read(fd, resp, sizeof(resp) - 1);");
  out.push("    if (n <= 0) { perror(\"read\"); return 1; }");
  out.push("    resp[n] = '\\0';");
  out.push("    if (!strstr(resp, \" 101 \")) { fprintf(stderr, \"握手失败: %s\\n\", resp); return 1; }");
  out.push("    printf(\">>> 握手成功\\n\");");
  out.push("");
  out.push("    /* 3. 初始化 wslay 并发送一条文本消息 */");
  out.push("    struct wslay_event_callbacks callbacks = {");
  out.push("        .recv_callback = recv_cb,");
  out.push("        .send_callback = send_cb,");
  out.push("        .genmask_callback = genmask_cb,");
  out.push("        .on_msg_recv_callback = msg_recv_cb,");
  out.push("    };");
  out.push("    wslay_event_context_ptr ctx;");
  out.push("    if (wslay_event_context_client_init(&ctx, &callbacks, &fd) != 0) {");
  out.push("        fprintf(stderr, \"wslay 初始化失败\\n\");");
  out.push("        return 1;");
  out.push("    }");
  out.push(`    const char *msg = ${JSON.stringify(r.message || "hello, this is a websocket echo message")};`);
  out.push("    wslay_event_queue_msg(ctx,");
  out.push("                          wslay_event_create_text_message((const uint8_t *)msg, strlen(msg)));");
  out.push("    printf(\">>> 发送: %s\\n\", msg);");
  out.push("    wslay_event_send(ctx);");
  out.push("");
  out.push("    /* 4. 接收回显（select 等待 5 秒，收到后退出） */");
  out.push("    while (!g_done) {");
  out.push("        fd_set rfds;");
  out.push("        FD_ZERO(&rfds);");
  out.push("        FD_SET(fd, &rfds);");
  out.push("        struct timeval tv = { 5, 0 };");
  out.push("        if (select(fd + 1, &rfds, NULL, NULL, &tv) <= 0) break;");
  out.push("        if (wslay_event_recv(ctx) != 0) break;");
  out.push("    }");
  out.push("    wslay_event_context_free(ctx);");
  out.push("    close(fd);");
  out.push("    return 0;");
  out.push("}");
  return out.join("\n");
}
